### ISSUE TITLE
issue with graphics.drawString() while trying to draw text leaning on the edge

### ISSUE THREAD

**Issue by helio-frota** [aeshell/aesh#179]
this happen when we try just print one char:

```java
graphics.drawString("1", width, 1);
graphics.drawString("12", width - 1, 2);
graphics.drawString("123", width - 2, 3);
```
![1](https://cloud.githubusercontent.com/assets/6443576/9110421/ec76233e-3c13-11e5-9927-f77e252bd246.png)

---

```java
graphics.drawString("1", width - 1, 1); // < -----
graphics.drawString("12", width - 1, 2);
graphics.drawString("123", width - 2, 3);
```

![2](https://cloud.githubusercontent.com/assets/6443576/9110489/6c98776a-3c14-11e5-9f37-47800ef3fbc7.png)

---

works for string with 2+ chars:

```java
graphics.drawString(" 1", width - 1, 1); // < ----- added blank char
graphics.drawString("12", width - 1, 2);
graphics.drawString("123", width - 2, 3);
```

![3](https://cloud.githubusercontent.com/assets/6443576/9110542/e9412fc8-3c14-11e5-9b1d-25951d569075.png)

**Comment by eprogramming** [comment]
When increasing the size of String we have a *safe border* or something like this, and the String goes to the left:

![4](https://cloud.githubusercontent.com/assets/6443576/9177553/33635a6c-3f68-11e5-864f-57d0b30cc6c0.png)


But by increasing the x Axis ( the width not the string) we can go through the screen but not by stopping on the edge: (graphics.drawString(str, xAxis **+ 1**, yAxis);

![5](https://cloud.githubusercontent.com/assets/6443576/9177606/7d44d796-3f68-11e5-8394-6105bbcd9033.png)
