### ISSUE TITLE
Antlr and aesh

### ISSUE THREAD

**Issue by bioinfornatics** [aeshell/aesh#239]
Dear, 
I would like to know if it  is possible to mixt Antlr and aesh callback. Indeed Antlr seem to be powerful to parse user input while aesh is able to use input (with completion support) and output console. 
Thanks for your help

**Comment by stalep** [comment]
Hi, yes it should be possible. Atm æsh can parse the input and inject it into commands, but the current "grammar" is fairly limited.
In the future I'm hoping to be able to implement a repl written in antlr in æsh that would mimic a bash syntax. - or even support some sort of pluggable repl.
