### ISSUE TITLE
Ansi Color Output?

### ISSUE THREAD

**Issue by buko** [aeshell/aesh#296]
Aesh looks like a really cool project. It even has graphics!

We're looking into commands that would print syntax-highlighted XML and JSon to the console... unless their output is being routed to a file or pipe in which case we don't want any Ansi highlight codes in the output.

How would you accomplish this with Aesh?

Is it possible to integrate Jansi (https://github.com/fusesource/jansi) with aesh? Jansi solves this problem nicely but it's not obvious how to integrate it with aesh.

**Comment by stalep** [comment]
Hi, sorry I didn't notice this comment before I went on PTO.
First, thanks for testing out æsh! 
Actually Æsh have this built in. If a command prints out ANSI codes in the output it will be stripped away from the output automatically if the output is piped to either a file or another command.
To easily print syntax-highlighted output you can use some of the classes form the æsh-readline project that Æsh consumes like org.aesh.readline.terminal.formatting.TerminalString/TerminalCharacter or just use the org.aesh.utils.ANSI class for more easily access to the ANSI codes.
If you use Windows Æsh will convert the ANSI codes into Windows compatible syntax. Sorry again for the late comment.
