### ISSUE TITLE
Split Packages Across aesh and aesh-readline

### ISSUE THREAD

**Issue by buko** [aeshell/aesh#309]
Am I missing something or do the latest versions of aesh (2.3 according to https://mvnrepository.com/artifact/org.aesh/aesh and 1.1.7 according to https://mvnrepository.com/artifact/org.aesh/aesh-readline) not actually fix the many split-package errors described in https://issues.jboss.org/browse/AESH-458?_sscc=t ?

As things stand now I can't seem to get aesh to work on JDK11. Is it supported at all?

Also, it might be a good idea to update https://github.com/aeshell/aesh/blob/master/README.asciidoc . The code described there doesn't actually work. Instead of including deprecated code it might make sense to link to https://github.com/aeshell/aesh/blob/master/examples/src/main/java/examples/SimpleExample.java. Links to code in the git repository won't go out of date.

**Comment by stalep** [comment]
Hi, sorry for the late reply. I just noticed the issue no (sorry, gotten too much spam from github).
I have been moving some of the examples to a aesh-examples repo (https://github.com/aeshell/aesh-examples), the plan is to remove all the current examples in aesh/aesh-readline very soon.
I'll also make sure that everything works on JDK11.

**Comment by buko** [comment]
The split packages is for us a blocker. We'd very much like to use aesh (instead of working directly with jline3) but there's really no good solution to the split packages. What's strange is that there are JIRA issues indicating the split packages issue was fixed but the latest versions of aesh from maven still have these issues. In addition to fixing the split package issue it would be great if aesh jars could add Automatic Module Names (http://branchandbound.net/blog/java/2017/12/automatic-module-name/) and provide stable module names.

**Comment by stalep** [comment]
I understand, I've moved some classes in readline areound and removed examples there. I'll look at æsh more now. Hopefully I'll do a new release this week. I'll try to have the Module Names in there as well, thanks for the comments!

**Comment by stalep** [comment]
With your request I've been looking into moving to JDK11 and using module-info.java. I need to verify if this is OK with Wildfly, we'll see. Else, I'll move back to JDK8, but if things work fine on JDK11 it should be a verification that the packages are OK.

**Comment by stalep** [comment]
Hi, so I've pushed out readline 1.18-SNAPSHOT and æsh 2.4-SNAPSHOT. the package names for readline have changed a bit to be more consistent, but æsh should remain the same. They all should have Automatic-Module-Name in their manifest.mf files.
Let me know if you have any issues.

**Comment by stalep** [comment]
Closing as this should be done for readline and æsh in master and in the next release.
