### ISSUE TITLE
Can't pass option with quotes

### ISSUE THREAD

**Issue by janinko** [aeshell/aesh#319]
I'm trying to use:
```
CommandRuntime runtime = AeshCommandRuntimeBuilder.builder().commandRegistry(registry).build();
runtime.executeCommand(line);
```
But can't figure out how to pass option with this value: `test=="some thing"`

Tried these things already:
`some command --query "name==\"some thing\""` => `test==\"some thing\"`
`some command --query name=="some thing"` => `test==some thing`
`some command --query "name=="\""some thing"\"""` => ` ` and unknown argument `"some thing`

Also the problem is that I already have String[] args and I need a way to concatenate them somehow first for aesh later split them again to the same things before concatenation.

**Comment by stalep** [comment]
Hi, sorry I didn't notice this issue before now.  Let me have a look!

**Comment by stalep** [comment]
hi @janinko, if you do: ```'test=="some thing"'``` it should work.

**Comment by janinko** [comment]
I need to convert arbitrary string X to Y in such a way that aesh then converts Y back to X.
If the string was `test=="someone's thing"` then enclosing this whole thing in `'` would not work
In the end I solved it by looking into aesh code and escaping all chars that aesh treats specially. I'm just affraid it will brake if some changes are done to the aesh parser.

**Comment by stalep** [comment]
Ah, I see. Well, we can perhaps add a flag for the parser to escape all chars if set or something?

**Comment by janinko** [comment]
Could it take also String... args?

**Comment by stalep** [comment]
> Could it take also String... args?

the .executeCommand(..) method you mean?

**Comment by janinko** [comment]
yup

**Comment by stalep** [comment]
executeCommand(String...) has been pushed now, I have not added any flag to escape all chars yet.
