### ISSUE TITLE
Aesh does not properly validate required argument

### ISSUE THREAD

**Issue by thescouser89** [aeshell/aesh#322]
Reproducer: https://github.com/thescouser89/aesh-reproducer
Aesh version: 2.6
Affects: https://github.com/project-ncl/bacon/issues/328

The CLI is configured to have 1 required argument and 1 optional flag (--flag) aesh CLI does not fail on missing argument if a boolean flag is specified.

Expected successful run:
```
java -jar <app> test helloworld --verbose
# or
java -jar <app> test helloworld
```
where 'test' is the command, and 'helloworld' the argument
if I run:
```
java -jar <app> test --verbose
```
I expect the CLI to fail with missing argument error. Instead, it happily moves ahead with further processing, setting the argument field to null.

**Comment by stalep** [comment]
Hi, I extended a test to try to verify what you saw, but I can't quite manage to reproduce it.
ref: https://github.com/aeshell/aesh/commit/77b6fb38361c6974c4b1d64560d895e2067e4d76

**Comment by stalep** [comment]
I also tested with a small example locally without being able to reproduce it, do you have a reproducer you could share?

**Comment by stalep** [comment]
@thescouser89 can you link me to a command I can test? :)

**Comment by thescouser89** [comment]
Hi yes! I added the reproducer in the description. The reproducer is in the README.md :)

**Comment by stalep** [comment]
Wow, how could I miss that! thanks!

**Comment by stalep** [comment]
@thescouser89 I think I've spotted the issue. The verbose option is set to overrideRequired: https://github.com/thescouser89/aesh-reproducer/blob/4d3343ce84feb98de8dee0096efc5a767768f566/src/main/java/TestMain.java#L17

When setting overrideRequired on an option, if that option is set, it would override other required options;
https://github.com/aeshell/aesh/blob/77b6fb38361c6974c4b1d64560d895e2067e4d76/aesh/src/main/java/org/aesh/command/option/Option.java#L101-L104

**Comment by thescouser89** [comment]
Oh so I should set this to false then to get it to work as intended? I probably thought that was something different.
