### ISSUE TITLE
generateHelp is broken with @Argument(required=true or askIfNotSet = true)

### ISSUE THREAD

**Issue by SilverLuke** [aeshell/aesh#329]
I have defined a command with `generateHelp = true` and an argument with `required` (same problem with `askIfNotSet`), when i test the command it will print the help message even if i have set the argument.
The problem is reversed when i use `@Option` with `askIfNotSet = true`, and when i try to print the help, the command will ask for the option and than print the help.

`generateHelp` should print the help if i type --help or -h and skip all the `require` or `askIfNotSet`, right?

<details>
  <summary>My Code</summary>
  
```
    @CommandDefinition(name = "login",
            activator = BeforeLoginActivator.class,
            generateHelp = true)
    public static class LoginCommand implements Command {

 /*       @Option(shortName = 'u', description = "Username for login", askIfNotSet = true)
        String username;
   */     @Argument(description = "Username for login", askIfNotSet = true)
        String username;

        @Override
        public CommandResult execute(CommandInvocation invocation) {
        ...
        }

```
</details>

**Comment by stalep** [comment]
Hi @SilverLuke, let me test and I'll come back to you!

**Comment by stalep** [comment]
Hi again, really sorry that this has been put off for so long, but I've not had time to look much at aesh in a long time. I'm looking at fixing this now. - and yes, you are correct in assuming that the `generateHelp` should skip all options marked with `require` or `askIfNotSet`.
